#!/bin/bash
# Fine-tune a LoRA adapter on Splunk Q&A data and load it into Ollama.
#
# Prerequisites:
#   1. Training data exists: training_data/combined_training.jsonl
#      (generated by run_ingest_qa.sh steps 1-4 or scripts/build_training_data.py)
#   2. NVIDIA GPU available (for training)
#   3. Ollama running on port 11430
#
# Usage:
#   bash docker_files/run_finetune.sh                    # Full pipeline
#   bash docker_files/run_finetune.sh --epochs 5         # More training epochs
#   bash docker_files/run_finetune.sh --export-only      # Re-export existing adapter
#   bash docker_files/run_finetune.sh --quantization q8_0  # Higher quality GGUF
#
# What this does:
#   1. Builds the finetune container (if needed)
#   2. Runs LoRA fine-tuning on training data (unsloth + QLoRA)
#   3. Exports adapter to GGUF format
#   4. Loads the model into Ollama via API
#   5. Tests the model with a sample query

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
EXTRA_ARGS="${*}"

MODEL_NAME="${OLLAMA_FINE_TUNED_MODEL:-splunk-assistant}"
OLLAMA_URL="${OLLAMA_BASE_URL:-http://127.0.0.1:11430}"

# Docker/Podman detection
if command -v podman &> /dev/null; then
  DOCKER_CMD="podman"
else
  DOCKER_CMD="docker"
fi
docker() { "$DOCKER_CMD" "$@"; }

cleanup() { docker rm -f chainlit_finetune 2>/dev/null || true; }
trap cleanup EXIT

echo ""
echo "============================================================"
echo "  LoRA Fine-tuning Pipeline"
echo "============================================================"

# ──────────────────────────────────────────────────────────────
# Step 0: Validate prerequisites
# ──────────────────────────────────────────────────────────────
TRAINING_FILE="$PROJECT_ROOT/training_data/combined_training.jsonl"
if [ ! -f "$TRAINING_FILE" ]; then
    echo "ERROR: Training data not found at $TRAINING_FILE"
    echo "Run first:  bash docker_files/run_ingest_qa.sh"
    exit 1
fi

TRAIN_COUNT=$(wc -l < "$TRAINING_FILE")
echo "  Training file: $TRAINING_FILE ($TRAIN_COUNT examples)"

if [ "$TRAIN_COUNT" -lt 10 ]; then
    echo "ERROR: Need at least 10 training examples, have $TRAIN_COUNT."
    exit 1
fi

# Check Ollama
if ! curl -sf "$OLLAMA_URL/" >/dev/null 2>&1; then
    echo "WARNING: Ollama not reachable at $OLLAMA_URL — will train but skip model creation."
    OLLAMA_AVAILABLE=false
else
    OLLAMA_AVAILABLE=true
fi

# ──────────────────────────────────────────────────────────────
# Step 1: Build finetune container (if needed)
# ──────────────────────────────────────────────────────────────
FINETUNE_IMAGE="chainlit-finetune:latest"
if ! docker image inspect "$FINETUNE_IMAGE" >/dev/null 2>&1; then
    # Try with localhost prefix (podman)
    FINETUNE_IMAGE="localhost/chainlit-finetune:latest"
    if ! docker image inspect "$FINETUNE_IMAGE" >/dev/null 2>&1; then
        echo ""
        echo "[Step 1/5] Building finetune container..."
        docker build -f "$SCRIPT_DIR/Dockerfile.finetune" -t chainlit-finetune:latest "$PROJECT_ROOT"
        FINETUNE_IMAGE="chainlit-finetune:latest"
    fi
fi
echo "[Step 1/5] Finetune image: $FINETUNE_IMAGE"

# ──────────────────────────────────────────────────────────────
# Step 2: Run LoRA fine-tuning
# ──────────────────────────────────────────────────────────────
echo ""
echo "[Step 2/5] Running LoRA fine-tuning (this uses GPU)..."

# Detect GPU support
GPU_FLAG=""
if [ "$DOCKER_CMD" = "podman" ]; then
    # Podman: try CDI device first, fall back to --device flag
    if podman info 2>/dev/null | grep -qi nvidia; then
        GPU_FLAG="--device nvidia.com/gpu=all --security-opt=label=disable"
    elif [ -e /dev/nvidia0 ]; then
        GPU_FLAG="--device /dev/nvidia0 --device /dev/nvidiactl --device /dev/nvidia-uvm"
    fi
else
    # Docker: use --gpus
    if docker info 2>/dev/null | grep -qi nvidia; then
        GPU_FLAG="--gpus all"
    fi
fi

if [ -z "$GPU_FLAG" ]; then
    echo "  WARNING: No GPU detected. Training will be very slow."
    echo "  For production, use a machine with an NVIDIA GPU."
fi

mkdir -p "$PROJECT_ROOT/training_data/adapter"

FT_CONTAINER="chainlit_finetune"
docker rm -f "$FT_CONTAINER" 2>/dev/null || true

docker create --name "$FT_CONTAINER" \
    $GPU_FLAG \
    -e OLLAMA_BASE_MODEL_NAME="${OLLAMA_BASE_MODEL:-qwen2.5:3b}" \
    "$FINETUNE_IMAGE" \
    --training-file /app/training_data/combined_training.jsonl \
    --output-dir /app/training_data/adapter \
    $EXTRA_ARGS

# Copy training data into container
docker cp "$PROJECT_ROOT/training_data" "$FT_CONTAINER:/app/training_data"

docker start -a "$FT_CONTAINER"

# Copy results back
docker cp "$FT_CONTAINER:/app/training_data/adapter" "$PROJECT_ROOT/training_data/adapter"
docker rm -f "$FT_CONTAINER" 2>/dev/null || true

# ──────────────────────────────────────────────────────────────
# Step 3: Verify GGUF output
# ──────────────────────────────────────────────────────────────
echo ""
echo "[Step 3/5] Checking GGUF adapter..."

GGUF_FILE=$(find "$PROJECT_ROOT/training_data/adapter" -name "*.gguf" -type f | head -1)
if [ -z "$GGUF_FILE" ]; then
    echo "ERROR: No GGUF file found in training_data/adapter/"
    exit 1
fi

GGUF_SIZE=$(du -h "$GGUF_FILE" | cut -f1)
echo "  GGUF adapter: $GGUF_FILE ($GGUF_SIZE)"

MODELFILE="$PROJECT_ROOT/training_data/adapter/Modelfile"
if [ ! -f "$MODELFILE" ]; then
    echo "ERROR: No Modelfile found"
    exit 1
fi
echo "  Modelfile: $MODELFILE"

# ──────────────────────────────────────────────────────────────
# Step 4: Create Ollama model
# ──────────────────────────────────────────────────────────────
echo ""
if [ "$OLLAMA_AVAILABLE" = true ]; then
    echo "[Step 4/5] Creating Ollama model '$MODEL_NAME'..."

    # The GGUF and Modelfile need to be accessible to Ollama.
    # If Ollama is in a container, we copy files there.
    # If Ollama is on host, we use the API with the Modelfile content.

    # Approach: use Ollama API with inline modelfile
    # But ADAPTER path must be accessible to Ollama. Copy GGUF to Ollama container.
    OLLAMA_CONTAINER=$(docker ps --format '{{.Names}}' | grep -E 'ollama|llm_api' | head -1 || true)

    if [ -n "$OLLAMA_CONTAINER" ]; then
        echo "  Copying adapter to Ollama container ($OLLAMA_CONTAINER)..."
        docker cp "$GGUF_FILE" "$OLLAMA_CONTAINER:/tmp/splunk-adapter.gguf"

        # Read base Modelfile and override ADAPTER path to container path
        GGUF_BASENAME=$(basename "$GGUF_FILE")
        OLLAMA_BASE="${OLLAMA_BASE_MODEL:-qwen2.5:3b}"

        docker exec "$OLLAMA_CONTAINER" bash -c "cat > /tmp/Modelfile <<'MFEOF'
FROM $OLLAMA_BASE
ADAPTER /tmp/splunk-adapter.gguf
PARAMETER temperature 0.2
PARAMETER top_p 0.9
PARAMETER num_ctx 4096
SYSTEM \"\"\"You are a Splunk expert assistant for the organization.
Key rules:
- Never use index=* — always specify the correct index
- Prefer | tstats with CIM data models for performance
- Use TERM() and PREFIX() inside tstats WHERE for index-level filtering
- TERM() = exact token match, PREFIX() = starts-with on indexed fields
- Break down saved searches stage by stage
- If unsure, ask clarifying questions\"\"\"
MFEOF
"
        echo "  Creating model..."
        docker exec "$OLLAMA_CONTAINER" ollama create "$MODEL_NAME" -f /tmp/Modelfile

        echo "  Model '$MODEL_NAME' created successfully."
    else
        echo "  WARNING: No Ollama container found. Create model manually:"
        echo "    ollama create $MODEL_NAME -f $MODELFILE"
    fi
else
    echo "[Step 4/5] Skipped (Ollama not available)"
    echo "  When Ollama is running, create the model with:"
    echo "    ollama create $MODEL_NAME -f $MODELFILE"
fi

# ──────────────────────────────────────────────────────────────
# Step 5: Test the model
# ──────────────────────────────────────────────────────────────
echo ""
if [ "$OLLAMA_AVAILABLE" = true ] && [ -n "${OLLAMA_CONTAINER:-}" ]; then
    echo "[Step 5/5] Testing model with sample query..."
    echo "  Query: 'Show failed login attempts in the last hour'"
    echo ""
    docker exec "$OLLAMA_CONTAINER" ollama run "$MODEL_NAME" \
        "Show failed login attempts in the last hour" 2>&1 | head -30
    echo ""
else
    echo "[Step 5/5] Skipped (model not loaded)"
fi

# ──────────────────────────────────────────────────────────────
# Summary
# ──────────────────────────────────────────────────────────────
echo ""
echo "============================================================"
echo "  Fine-tuning complete!"
echo "============================================================"
echo ""
echo "  Training examples:  $TRAIN_COUNT"
echo "  GGUF adapter:       $GGUF_FILE ($GGUF_SIZE)"
echo "  Modelfile:          $MODELFILE"
echo "  Ollama model:       $MODEL_NAME"
echo ""
echo "  To use in the chatbot, set:"
echo "    OLLAMA_MODEL=$MODEL_NAME"
echo ""
echo "  To re-train after more feedback accumulates:"
echo "    bash docker_files/run_ingest_qa.sh    # regenerate training data"
echo "    bash docker_files/run_finetune.sh     # retrain"
echo ""
