"""
Skill catalog data (group A): Cognitive, IO, Communication, Alerting, Creative, Social skills.

Part of the SKILL_CATALOG data split for maintainability.
Re-exported via skill_catalog.py as part of the combined SKILL_CATALOG list.
"""
from chat_app.skill_catalog_types import Skill, SkillFamily, ApprovalGate  # noqa: F401


SKILL_CATALOG_A = [
    # COGNITIVE SKILLS — Think, Reason, Analyze, Plan, Learn, Remember
    # =====================================================================
    Skill(
        action="think", name="reason",
        description="Analyze a problem using multi-step reasoning (ReAct loop)",
        family=SkillFamily.COGNITIVE, emoji="🧠",
        handler_key="react_loop",
        intents=["spl_generation", "troubleshooting", "analysis"],
        tags=["reasoning", "analysis"],
    ),
    Skill(
        action="analyze", name="analyze_spl",
        description="Analyze SPL queries for performance issues, anti-patterns, and optimization opportunities",
        family=SkillFamily.COGNITIVE, emoji="🔬",
        handler_key="analyze_spl",
        intents=["spl_generation", "spl_optimization"],
        tags=["spl", "analysis", "performance"],
    ),
    Skill(
        action="evaluate", name="evaluate_quality",
        description="Score and evaluate response quality using self-evaluation metrics",
        family=SkillFamily.COGNITIVE, emoji="⚖️",
        handler_key="self_evaluator",
        intents=["quality"],
        tags=["quality", "evaluation"],
    ),
    Skill(
        action="plan", name="plan_actions",
        description="Create an execution plan for multi-step queries",
        family=SkillFamily.COGNITIVE, emoji="📋",
        handler_key="query_planner",
        intents=["spl_generation", "troubleshooting"],
        tags=["planning", "multi-step"],
    ),
    Skill(
        action="decide", name="classify_intent",
        description="Classify user intent and route to the appropriate handler",
        family=SkillFamily.COGNITIVE, emoji="🎯",
        handler_key="intent_classifier",
        intents=["routing"],
        tags=["intent", "routing", "classification"],
    ),
    Skill(
        action="learn", name="self_learn",
        description="Learn from interactions to improve future responses (episodic memory)",
        family=SkillFamily.COGNITIVE, emoji="📚",
        handler_key="episodic_memory",
        intents=["learning"],
        tags=["learning", "improvement", "memory"],
    ),
    Skill(
        action="remember", name="recall_context",
        description="Recall relevant context from previous interactions and knowledge base",
        family=SkillFamily.COGNITIVE, emoji="💭",
        handler_key="context_builder",
        intents=["retrieval"],
        tags=["context", "memory", "retrieval"],
    ),
    Skill(
        action="focus", name="compress_context",
        description="Compress and prioritize context to fit within token budgets",
        family=SkillFamily.COGNITIVE, emoji="🎯",
        handler_key="context_compressor",
        intents=["optimization"],
        tags=["compression", "focus", "tokens"],
    ),
    Skill(
        action="score", name="score_confidence",
        description="Calculate confidence scores for responses using multi-factor analysis",
        family=SkillFamily.COGNITIVE, emoji="📊",
        handler_key="confidence_scorer",
        intents=["quality"],
        tags=["confidence", "scoring"],
    ),
    Skill(
        action="diagnose", name="diagnose_failure",
        description="Categorize and diagnose failures with recovery suggestions",
        family=SkillFamily.COGNITIVE, emoji="🩺",
        handler_key="failure_analyzer",
        intents=["troubleshooting"],
        tags=["diagnosis", "failure", "recovery"],
    ),
    Skill(
        action="judge", name="validate_spl",
        description="Validate SPL syntax and check for dangerous patterns",
        family=SkillFamily.COGNITIVE, emoji="⚡",
        handler_key="validate_spl",
        intents=["spl_generation"],
        tags=["validation", "spl", "syntax"],
    ),
    Skill(
        action="compare", name="compare_configs",
        description="Compare configurations, queries, or results side-by-side",
        family=SkillFamily.COGNITIVE, emoji="🔄",
        handler_key="compare",
        intents=["config_lookup", "analysis"],
        tags=["comparison", "diff"],
    ),

    # =====================================================================
    # IO SKILLS — Eat (Ingest), Run (Search), Walk (Browse), Jump (Escalate)
    # =====================================================================
    Skill(
        action="eat", name="ingest_data",
        description="Ingest and consume data from files, URLs, or documents into the knowledge base",
        family=SkillFamily.IO, emoji="🍽️",
        handler_key="ingest_document",
        approval=ApprovalGate.CONFIRM,
        intents=["ingest", "upload", "learn"],
        tags=["ingestion", "data", "input"],
    ),
    Skill(
        action="run", name="execute_search",
        description="Execute SPL searches against the connected Splunk instance",
        family=SkillFamily.IO, emoji="🏃",
        handler_key="run_splunk_search",
        requires={"splunk_connected"},
        intents=["run_search"],
        tags=["search", "execution", "splunk"],
    ),
    Skill(
        action="walk", name="browse_knowledge",
        description="Browse and explore the knowledge base, collections, and documents",
        family=SkillFamily.IO, emoji="🚶",
        handler_key="search_knowledge",
        intents=["search", "knowledge", "lookup"],
        tags=["browse", "explore", "knowledge"],
    ),
    Skill(
        action="jump", name="escalate_issue",
        description="Escalate critical issues to admin review or human-in-the-loop",
        family=SkillFamily.IO, emoji="🦘",
        handler_key="escalate",
        approval=ApprovalGate.REVIEW,
        intents=["escalation"],
        tags=["escalation", "critical", "admin"],
    ),
    Skill(
        action="swim", name="deep_dive_analysis",
        description="Perform deep-dive analysis with extensive context retrieval and multi-pass reasoning",
        family=SkillFamily.IO, emoji="🏊",
        handler_key="deep_analysis",
        intents=["analysis", "troubleshooting"],
        tags=["deep-dive", "thorough", "analysis"],
    ),
    Skill(
        action="fetch", name="retrieve_chunks",
        description="Fetch relevant document chunks from the vector store",
        family=SkillFamily.IO, emoji="🐕",
        handler_key="search_knowledge_base",
        intents=["retrieval", "search"],
        tags=["retrieval", "vector", "chunks"],
    ),
    Skill(
        action="grab", name="extract_fields",
        description="Extract specific fields, patterns, or values from data",
        family=SkillFamily.IO, emoji="🤏",
        handler_key="extract",
        intents=["extraction"],
        tags=["extraction", "fields", "patterns"],
    ),
    Skill(
        action="pour", name="export_results",
        description="Export search results, reports, or configurations to files",
        family=SkillFamily.IO, emoji="🫗",
        handler_key="export",
        approval=ApprovalGate.CONFIRM,
        intents=["export"],
        tags=["export", "output", "results"],
    ),
    Skill(
        action="dig", name="search_deep",
        description="Deep search across multiple indices, sourcetypes, and time ranges",
        family=SkillFamily.IO, emoji="⛏️",
        handler_key="deep_search",
        requires={"splunk_connected"},
        intents=["search", "investigation"],
        tags=["deep-search", "investigation"],
    ),

    # =====================================================================
    # COMMUNICATION SKILLS — Speak, Listen, Write, Read, Explain, Teach
    # =====================================================================
    Skill(
        action="speak", name="generate_response",
        description="Generate natural language responses synthesizing RAG context and tool results",
        family=SkillFamily.COMMUNICATION, emoji="🗣️",
        handler_key="response_generator",
        intents=["response"],
        tags=["response", "generation", "nlp"],
    ),
    Skill(
        action="listen", name="parse_input",
        description="Parse and understand user input, extracting intent, entities, and context",
        family=SkillFamily.COMMUNICATION, emoji="👂",
        handler_key="intent_classifier",
        intents=["routing", "parsing"],
        tags=["parsing", "understanding", "input"],
    ),
    Skill(
        action="write", name="generate_spl",
        description="Write/generate SPL queries from natural language descriptions",
        family=SkillFamily.COMMUNICATION, emoji="✍️",
        handler_key="generate_spl",
        intents=["spl_generation", "nlp_to_spl"],
        tags=["generation", "spl", "writing"],
    ),
    Skill(
        action="read", name="parse_document",
        description="Read and parse documents (.conf files, SPL docs, markdown, specs)",
        family=SkillFamily.COMMUNICATION, emoji="📖",
        handler_key="conf_parser",
        intents=["parsing", "ingestion"],
        tags=["reading", "parsing", "documents"],
    ),
    Skill(
        action="explain", name="explain_spl",
        description="Explain SPL queries step-by-step in plain language",
        family=SkillFamily.COMMUNICATION, emoji="💡",
        handler_key="explain_spl",
        intents=["spl_generation"],
        tags=["explanation", "teaching", "spl"],
    ),
    Skill(
        action="document", name="generate_documentation",
        description="Generate professional documentation from code, configs, text snippets, or directories",
        family=SkillFamily.COMMUNICATION, emoji="📝",
        handler_key="doc_generator",
        intents=["general_qa"],
        tags=["documentation", "generation", "writing", "markdown", "sharepoint"],
        min_role="USER",
    ),
    Skill(
        action="teach", name="teach_concept",
        description="Teach Splunk/observability concepts with examples and best practices",
        family=SkillFamily.COMMUNICATION, emoji="🎓",
        handler_key="teach",
        intents=["general_qa", "meta_question"],
        tags=["teaching", "education", "concepts"],
    ),
    Skill(
        action="ask", name="request_clarification",
        description="Ask the user for clarification when intent or requirements are ambiguous",
        family=SkillFamily.COMMUNICATION, emoji="❓",
        handler_key="clarification",
        intents=["clarification"],
        tags=["clarification", "questions"],
    ),
    Skill(
        action="answer", name="answer_question",
        description="Answer general questions using RAG context and knowledge base",
        family=SkillFamily.COMMUNICATION, emoji="💬",
        handler_key="general_qa",
        intents=["general_qa"],
        tags=["answers", "qa"],
    ),
    Skill(
        action="translate", name="translate_query",
        description="Translate between natural language and SPL, or between SPL dialects",
        family=SkillFamily.COMMUNICATION, emoji="🌐",
        handler_key="nlp_to_spl",
        intents=["spl_generation", "nlp_to_spl"],
        tags=["translation", "spl", "nlp"],
    ),
    Skill(
        action="annotate", name="annotate_spl",
        description="Add inline comments and annotations to SPL queries",
        family=SkillFamily.COMMUNICATION, emoji="📝",
        handler_key="annotate_spl",
        intents=["spl_generation"],
        tags=["annotation", "comments", "spl"],
    ),
    Skill(
        action="summarize", name="summarize_results",
        description="Summarize search results, config findings, or analysis into concise reports",
        family=SkillFamily.COMMUNICATION, emoji="📄",
        handler_key="summarize",
        intents=["reporting"],
        tags=["summary", "report", "concise"],
    ),

    # =====================================================================
    # ALERTING SKILLS — Cry (Alert), Worry (Warn), Calm (Stabilize)
    # =====================================================================
    Skill(
        action="cry", name="trigger_alert",
        description="Create and trigger alerts for critical conditions",
        family=SkillFamily.ALERTING, emoji="🚨",
        handler_key="create_alert",
        approval=ApprovalGate.CONFIRM,
        intents=["create_alert"],
        tags=["alerting", "notification", "critical"],
    ),
    Skill(
        action="worry", name="warn_issues",
        description="Warn about potential issues, anti-patterns, or security vulnerabilities",
        family=SkillFamily.ALERTING, emoji="⚠️",
        handler_key="knowledge_gap",
        intents=["troubleshooting", "config_health_check"],
        tags=["warning", "issues", "gaps"],
    ),
    Skill(
        action="calm", name="stabilize_system",
        description="Suggest stabilization steps for degraded system states",
        family=SkillFamily.ALERTING, emoji="🧘",
        handler_key="stabilize",
        intents=["troubleshooting"],
        tags=["stabilization", "recovery"],
    ),
    Skill(
        action="shout", name="critical_notification",
        description="Send critical notifications for urgent system events",
        family=SkillFamily.ALERTING, emoji="📢",
        handler_key="notify_critical",
        approval=ApprovalGate.REVIEW,
        intents=["escalation", "critical"],
        tags=["critical", "urgent", "notification"],
    ),
    Skill(
        action="whisper", name="suggest_quietly",
        description="Provide subtle suggestions and hints without overwhelming the user",
        family=SkillFamily.ALERTING, emoji="🤫",
        handler_key="search_suggestion",
        intents=["search_suggestion"],
        tags=["suggestion", "hint", "subtle"],
    ),

    # =====================================================================
    # CREATIVE SKILLS — Play (Experiment), Build, Create, Design, Compose
    # =====================================================================
    Skill(
        action="play", name="experiment",
        description="Experiment with different SPL approaches, test hypotheses",
        family=SkillFamily.CREATIVE, emoji="🎮",
        handler_key="experiment",
        intents=["spl_generation", "optimization"],
        tags=["experiment", "testing", "exploration"],
    ),
    Skill(
        action="build", name="build_pipeline",
        description="Build data processing pipelines (Cribl, Splunk HEC, forwarder chains)",
        family=SkillFamily.CREATIVE, emoji="🔨",
        handler_key="analyze_cribl_pipeline",
        intents=["cribl_pipeline"],
        tags=["pipeline", "building", "cribl"],
    ),
    Skill(
        action="create", name="create_dashboard",
        description="Create dashboard definitions, saved searches, and report configurations",
        family=SkillFamily.CREATIVE, emoji="🎨",
        handler_key="create_dashboard",
        approval=ApprovalGate.CONFIRM,
        intents=["create_alert", "reporting"],
        tags=["creation", "dashboard", "reports"],
    ),
    Skill(
        action="design", name="design_architecture",
        description="Design data architecture, index strategy, and deployment topology",
        family=SkillFamily.CREATIVE, emoji="📐",
        handler_key="design",
        intents=["config_lookup", "architecture"],
        tags=["design", "architecture", "strategy"],
    ),
    Skill(
        action="compose", name="compose_query",
        description="Compose complex multi-stage SPL queries from building blocks",
        family=SkillFamily.CREATIVE, emoji="🎼",
        handler_key="spl_template_engine",
        intents=["spl_generation"],
        tags=["composition", "spl", "templates"],
    ),
    Skill(
        action="improvise", name="adaptive_response",
        description="Adaptively modify approach based on intermediate results",
        family=SkillFamily.CREATIVE, emoji="🎭",
        handler_key="react_loop",
        intents=["troubleshooting", "analysis"],
        tags=["adaptive", "dynamic"],
    ),
    Skill(
        action="craft", name="craft_config",
        description="Craft Splunk .conf file stanzas with proper syntax and best practices",
        family=SkillFamily.CREATIVE, emoji="🪡",
        handler_key="config_generator",
        intents=["config_lookup"],
        tags=["config", "crafting", "stanzas"],
    ),

    # =====================================================================
    # SOCIAL SKILLS — Collaborate, Delegate, Lead, Mentor
    # =====================================================================
    Skill(
        action="collaborate", name="multi_agent_task",
        description="Coordinate multiple agent personas to solve complex problems",
        family=SkillFamily.SOCIAL, emoji="🤝",
        handler_key="orchestrator",
        intents=["complex_task"],
        tags=["collaboration", "coordination"],
    ),
    Skill(
        action="delegate", name="assign_to_agent",
        description="Delegate sub-tasks to specialized agent personas",
        family=SkillFamily.SOCIAL, emoji="📤",
        handler_key="agent_dispatch",
        intents=["complex_task"],
        tags=["delegation", "agents"],
    ),
    Skill(
        action="lead", name="orchestrate_workflow",
        description="Lead and orchestrate multi-step workflows across agents and skills",
        family=SkillFamily.SOCIAL, emoji="🎖️",
        handler_key="workflow_orchestrator",
        intents=["complex_task", "pipeline"],
        tags=["leadership", "orchestration"],
    ),
    Skill(
        action="mentor", name="guide_user",
        description="Guide the user through complex tasks with step-by-step assistance",
        family=SkillFamily.SOCIAL, emoji="🧑‍🏫",
        handler_key="guided_mode",
        intents=["teaching", "onboarding"],
        tags=["mentoring", "guidance"],
    ),
    Skill(
        action="negotiate", name="resolve_conflict",
        description="Resolve conflicting information from multiple sources",
        family=SkillFamily.SOCIAL, emoji="🤝",
        handler_key="conflict_resolution",
        intents=["analysis"],
        tags=["resolution", "conflict"],
    ),
    Skill(
        action="follow", name="execute_instruction",
        description="Follow explicit user instructions precisely without deviation",
        family=SkillFamily.SOCIAL, emoji="👣",
        handler_key="direct_execution",
        intents=["run_search", "create_alert"],
        tags=["execution", "instruction"],
    ),

    # =====================================================================
    # MAINTENANCE SKILLS — Sleep (Rest), Heal (Recover), Clean, Protect
    # =====================================================================
    Skill(
        action="sleep", name="idle_mode",
        description="Enter idle/maintenance mode — perform background self-improvement tasks",
        family=SkillFamily.MAINTENANCE, emoji="😴",
        handler_key="idle_worker",
        intents=["maintenance"],
        tags=["idle", "background", "maintenance"],
    ),
    Skill(
        action="heal", name="self_repair",
        description="Self-repair by detecting and recovering from degraded states",
        family=SkillFamily.MAINTENANCE, emoji="💚",
        handler_key="health_monitor",
        intents=["health", "recovery"],
        tags=["healing", "recovery", "repair"],
    ),
    Skill(
        action="clean", name="purge_stale",
        description="Clean up stale data, expired caches, and old backups",
        family=SkillFamily.MAINTENANCE, emoji="🧹",
        handler_key="cleanup",
        approval=ApprovalGate.CONFIRM,
        intents=["maintenance"],
        tags=["cleanup", "purge", "maintenance"],
    ),
    Skill(
        action="protect", name="security_check",
        description="Check for security vulnerabilities, dangerous SPL, and exposed credentials",
        family=SkillFamily.MAINTENANCE, emoji="🛡️",
        handler_key="security_audit",
        intents=["security", "config_health_check"],
        tags=["security", "protection", "audit"],
    ),
    Skill(
        action="organize", name="organize_knowledge",
        description="Organize and optimize the knowledge base structure and collections",
        family=SkillFamily.MAINTENANCE, emoji="🗂️",
        handler_key="organize",
        intents=["maintenance"],
        tags=["organization", "structure"],
    ),
    Skill(
        action="stretch", name="warm_up",
        description="Pre-warm caches, load frequently used models, prepare for queries",
        family=SkillFamily.MAINTENANCE, emoji="🤸",
        handler_key="warmup",
        intents=["initialization"],
        tags=["warmup", "preparation"],
    ),
    Skill(
        action="rest", name="reduce_load",
        description="Reduce system load during high-pressure periods (throttling, graceful degradation)",
        family=SkillFamily.MAINTENANCE, emoji="🛋️",
        handler_key="throttle",
        intents=["maintenance"],
        tags=["throttling", "load-reduction"],
    ),

    # =====================================================================
]
