"""
Skill catalog data (group B): Maintenance, Operational, and Utility skills.

Part of the SKILL_CATALOG data split for maintainability.
Re-exported via skill_catalog.py as part of the combined SKILL_CATALOG list.
"""
from chat_app.skill_catalog_types import Skill, SkillFamily, ApprovalGate  # noqa: F401


SKILL_CATALOG_B = [
    # OPERATIONAL SKILLS — Optimize, Monitor, Route, Transform, Schedule
    # =====================================================================
    Skill(
        action="optimize", name="optimize_spl",
        description="Optimize SPL queries for performance (tstats conversion, TERM/PREFIX, field pruning)",
        family=SkillFamily.OPERATIONAL, emoji="⚡",
        handler_key="optimize_spl",
        intents=["spl_generation", "spl_optimization"],
        tags=["optimization", "performance", "spl"],
    ),
    Skill(
        action="monitor", name="monitor_health",
        description="Monitor system health, resource usage, and service connectivity",
        family=SkillFamily.OPERATIONAL, emoji="📡",
        handler_key="check_system_health",
        intents=["health", "monitoring"],
        tags=["monitoring", "health"],
    ),
    Skill(
        action="route", name="route_query",
        description="Route queries to the appropriate handler based on intent classification",
        family=SkillFamily.OPERATIONAL, emoji="🔀",
        handler_key="query_router",
        intents=["routing"],
        tags=["routing", "dispatch"],
    ),
    Skill(
        action="transform", name="transform_data",
        description="Transform data formats (JSON to table, SPL to natural language, conf to YAML)",
        family=SkillFamily.OPERATIONAL, emoji="🔄",
        handler_key="transform",
        intents=["transformation"],
        tags=["transformation", "conversion"],
    ),
    Skill(
        action="schedule", name="schedule_task",
        description="Schedule recurring tasks (saved searches, reports, alerts, health checks)",
        family=SkillFamily.OPERATIONAL, emoji="📅",
        handler_key="scheduler",
        approval=ApprovalGate.CONFIRM,
        intents=["create_alert", "reporting"],
        tags=["scheduling", "automation"],
    ),
    Skill(
        action="filter", name="filter_results",
        description="Filter and refine search results, chunks, or recommendations",
        family=SkillFamily.OPERATIONAL, emoji="🔍",
        handler_key="filter",
        intents=["search", "retrieval"],
        tags=["filtering", "refinement"],
    ),
    Skill(
        action="aggregate", name="aggregate_data",
        description="Aggregate and combine data from multiple sources or time periods",
        family=SkillFamily.OPERATIONAL, emoji="📊",
        handler_key="aggregate",
        intents=["analysis", "reporting"],
        tags=["aggregation", "combination"],
    ),
    Skill(
        action="cache", name="cache_results",
        description="Cache frequently accessed results for faster retrieval",
        family=SkillFamily.OPERATIONAL, emoji="💾",
        handler_key="cache",
        intents=["optimization"],
        tags=["caching", "performance"],
    ),
    Skill(
        action="deploy", name="deploy_config",
        description="Deploy configurations to Splunk instances (with approval gate)",
        family=SkillFamily.OPERATIONAL, emoji="🚀",
        handler_key="deploy",
        approval=ApprovalGate.REVIEW,
        requires={"splunk_connected"},
        intents=["deployment"],
        tags=["deployment", "config"],
    ),
    Skill(
        action="rollback", name="rollback_change",
        description="Rollback recent configuration changes using backup system",
        family=SkillFamily.OPERATIONAL, emoji="⏪",
        handler_key="rollback",
        approval=ApprovalGate.CONFIRM,
        intents=["recovery"],
        tags=["rollback", "recovery"],
    ),
    Skill(
        action="audit", name="audit_trail",
        description="Review audit trail of all system actions and configuration changes",
        family=SkillFamily.OPERATIONAL, emoji="📋",
        handler_key="audit",
        intents=["security", "compliance"],
        tags=["audit", "compliance", "trail"],
    ),
    Skill(
        action="measure", name="collect_metrics",
        description="Collect and report on system performance metrics",
        family=SkillFamily.OPERATIONAL, emoji="📏",
        handler_key="analyze_metrics",
        intents=["observability_metrics"],
        tags=["metrics", "measurement"],
    ),

    # =====================================================================
    # ANSIBLE / AUTOMATION SKILLS
    # =====================================================================
    Skill(
        action="validate", name="ansible_validate",
        description="Validate Ansible playbook YAML structure and best practices",
        family=SkillFamily.OPERATIONAL, emoji="✅",
        handler_key="ansible_validate_playbook",
        intents=["ansible", "automation"],
        tags=["ansible", "playbook", "validate", "yaml"],
    ),
    Skill(
        action="automate", name="ansible_generate",
        description="Generate Ansible playbooks from natural language descriptions",
        family=SkillFamily.OPERATIONAL, emoji="🤖",
        handler_key="ansible_generate_playbook",
        intents=["ansible", "automation"],
        tags=["ansible", "playbook", "generate"],
    ),
    Skill(
        action="explain_playbook", name="ansible_explain",
        description="Explain Ansible playbook structure, modules, and flow",
        family=SkillFamily.OPERATIONAL, emoji="📖",
        handler_key="ansible_explain_playbook",
        intents=["ansible", "automation"],
        tags=["ansible", "playbook", "explain"],
    ),
    Skill(
        action="improve_playbook", name="ansible_improve",
        description="Suggest improvements for Ansible playbook quality and security",
        family=SkillFamily.OPERATIONAL, emoji="🔧",
        handler_key="ansible_improve_playbook",
        intents=["ansible", "automation"],
        tags=["ansible", "playbook", "improve", "lint"],
    ),
    Skill(
        action="lookup_module", name="ansible_reference",
        description="Look up Ansible module reference with syntax and examples",
        family=SkillFamily.OPERATIONAL, emoji="📚",
        handler_key="ansible_module_reference",
        intents=["ansible", "automation"],
        tags=["ansible", "module", "reference"],
    ),

    # =====================================================================
    # SHELL SCRIPTING SKILLS
    # =====================================================================
    Skill(
        action="analyze_shell", name="shell_analyze",
        description="Analyze shell scripts for common issues and best practices",
        family=SkillFamily.OPERATIONAL, emoji="🔍",
        handler_key="shell_analyze_script",
        intents=["shell_script", "scripting"],
        tags=["shell", "bash", "analyze", "lint"],
    ),
    Skill(
        action="generate_shell", name="shell_generate",
        description="Generate shell scripts from descriptions with proper error handling",
        family=SkillFamily.OPERATIONAL, emoji="📝",
        handler_key="shell_generate_script",
        intents=["shell_script", "scripting"],
        tags=["shell", "bash", "generate"],
    ),
    Skill(
        action="improve_shell", name="shell_improve",
        description="Suggest improvements for shell script quality and safety",
        family=SkillFamily.OPERATIONAL, emoji="⬆️",
        handler_key="shell_improve_script",
        intents=["shell_script", "scripting"],
        tags=["shell", "bash", "improve"],
    ),
    Skill(
        action="explain_shell", name="shell_explain",
        description="Explain shell scripts line by line with command descriptions",
        family=SkillFamily.OPERATIONAL, emoji="💡",
        handler_key="shell_explain_script",
        intents=["shell_script", "scripting"],
        tags=["shell", "bash", "explain"],
    ),

    # =====================================================================
    # PYTHON SCRIPTING SKILLS
    # =====================================================================
    Skill(
        action="analyze_python", name="python_analyze",
        description="Analyze Python scripts for anti-patterns and security issues",
        family=SkillFamily.OPERATIONAL, emoji="🐍",
        handler_key="python_analyze_script",
        intents=["python_script", "scripting"],
        tags=["python", "analyze", "lint"],
    ),
    Skill(
        action="generate_python", name="python_generate",
        description="Generate Python scripts with proper structure and best practices",
        family=SkillFamily.OPERATIONAL, emoji="🐍",
        handler_key="python_generate_script",
        intents=["python_script", "scripting"],
        tags=["python", "generate"],
    ),
    Skill(
        action="improve_python", name="python_improve",
        description="Suggest improvements for Python code quality and typing",
        family=SkillFamily.OPERATIONAL, emoji="🐍",
        handler_key="python_improve_script",
        intents=["python_script", "scripting"],
        tags=["python", "improve"],
    ),
    Skill(
        action="explain_python", name="python_explain",
        description="Explain Python scripts structure, classes, and logic flow",
        family=SkillFamily.OPERATIONAL, emoji="🐍",
        handler_key="python_explain_script",
        intents=["python_script", "scripting"],
        tags=["python", "explain"],
    ),

    # --- Splunk Writer Skills (REVIEW approval) ---
    Skill(
        action="update_search", name="update_saved_search",
        description="Update an existing Splunk saved search (query, schedule, description)",
        family=SkillFamily.OPERATIONAL, emoji="✏️",
        handler_key="update_saved_search",
        approval=ApprovalGate.REVIEW,
        requires={"splunk_connected"},
        intents=["saved_search_analysis", "spl_optimization"],
        tags=["splunk", "saved_search", "write", "update"],
    ),
    Skill(
        action="create_object", name="create_knowledge_object",
        description="Create a Splunk knowledge object (macro, eventtype, tag, saved search)",
        family=SkillFamily.OPERATIONAL, emoji="🆕",
        handler_key="create_knowledge_object",
        approval=ApprovalGate.REVIEW,
        requires={"splunk_connected"},
        intents=["saved_search_analysis", "config_health_check"],
        tags=["splunk", "knowledge_object", "write", "create"],
    ),

    # =====================================================================
    # SPLUNK ADMIN READ SKILLS
    # =====================================================================
    Skill(
        action="list_indexes", name="list_splunk_indexes",
        description="List all Splunk indexes with size, event count, and retention",
        family=SkillFamily.OPERATIONAL, emoji="📊",
        handler_key="list_indexes",
        requires={"splunk_connected"},
        intents=["troubleshooting", "general_qa"],
        tags=["splunk", "indexes", "admin", "read"],
    ),
    Skill(
        action="list_inputs", name="list_splunk_inputs",
        description="List Splunk data inputs (monitors, TCP, UDP, HEC)",
        family=SkillFamily.OPERATIONAL, emoji="📥",
        handler_key="list_inputs",
        requires={"splunk_connected"},
        intents=["troubleshooting", "general_qa"],
        tags=["splunk", "inputs", "admin", "read"],
    ),
    Skill(
        action="list_apps", name="list_splunk_apps",
        description="List installed Splunk apps with version and status",
        family=SkillFamily.OPERATIONAL, emoji="📦",
        handler_key="list_apps",
        requires={"splunk_connected"},
        intents=["general_qa", "troubleshooting"],
        tags=["splunk", "apps", "admin", "read"],
    ),
    Skill(
        action="list_splunk_users", name="list_splunk_users",
        description="List Splunk users with their roles",
        family=SkillFamily.OPERATIONAL, emoji="👥",
        handler_key="list_users",
        requires={"splunk_connected"},
        intents=["general_qa", "troubleshooting"],
        tags=["splunk", "users", "admin", "read"],
    ),
    Skill(
        action="server_info", name="get_splunk_server_info",
        description="Get Splunk server info (version, OS, license, cluster status)",
        family=SkillFamily.OPERATIONAL, emoji="🖥️",
        handler_key="get_server_info",
        requires={"splunk_connected"},
        intents=["troubleshooting", "general_qa"],
        tags=["splunk", "server", "admin", "read"],
    ),
    Skill(
        action="list_deployment_clients", name="list_deployment_clients",
        description="List deployment server clients and their server classes",
        family=SkillFamily.OPERATIONAL, emoji="📡",
        handler_key="list_deployment_clients",
        requires={"splunk_connected"},
        intents=["troubleshooting"],
        tags=["splunk", "deployment", "forwarders", "admin", "read"],
    ),
    Skill(
        action="index_stats", name="search_index_stats",
        description="Get per-index ingestion rates, sizes, and license usage",
        family=SkillFamily.OPERATIONAL, emoji="📈",
        handler_key="search_index_stats",
        requires={"splunk_connected"},
        intents=["troubleshooting", "general_qa"],
        tags=["splunk", "indexes", "stats", "admin", "read"],
    ),
    Skill(
        action="list_lookups", name="list_splunk_lookups",
        description="List Splunk lookup files and definitions",
        family=SkillFamily.OPERATIONAL, emoji="🔍",
        handler_key="list_lookups",
        requires={"splunk_connected"},
        intents=["general_qa", "config_lookup"],
        tags=["splunk", "lookups", "admin", "read"],
    ),
    Skill(
        action="list_macros", name="list_splunk_macros",
        description="List Splunk search macros with their definitions",
        family=SkillFamily.OPERATIONAL, emoji="📝",
        handler_key="list_macros",
        requires={"splunk_connected"},
        intents=["general_qa", "config_lookup"],
        tags=["splunk", "macros", "admin", "read"],
    ),
    Skill(
        action="license_usage", name="get_license_usage",
        description="Get current Splunk license consumption vs entitlement",
        family=SkillFamily.OPERATIONAL, emoji="📋",
        handler_key="get_license_usage",
        requires={"splunk_connected"},
        intents=["troubleshooting", "general_qa"],
        tags=["splunk", "license", "admin", "read"],
    ),

    # =====================================================================
    # UTILITY SKILLS — Encoding, Hashing, Data Transforms, Validation
    # =====================================================================
    Skill(
        action="base64_encode", name="base64_encode",
        description="Encode text to base64",
        family=SkillFamily.OPERATIONAL, handler_key="base64_encode",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["encoding", "base64", "utility"],
    ),
    Skill(
        action="base64_decode", name="base64_decode",
        description="Decode base64 text back to plain text",
        family=SkillFamily.OPERATIONAL, handler_key="base64_decode",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["decoding", "base64", "utility"],
    ),
    Skill(
        action="url_encode", name="url_encode",
        description="URL-encode text (percent encoding)",
        family=SkillFamily.OPERATIONAL, handler_key="url_encode",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["encoding", "url", "utility"],
    ),
    Skill(
        action="url_decode", name="url_decode",
        description="Decode URL-encoded (percent encoded) text",
        family=SkillFamily.OPERATIONAL, handler_key="url_decode",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["decoding", "url", "utility"],
    ),
    Skill(
        action="hex_encode", name="hex_encode",
        description="Encode text to hexadecimal representation",
        family=SkillFamily.OPERATIONAL, handler_key="hex_encode",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["encoding", "hex", "utility"],
    ),
    Skill(
        action="hex_decode", name="hex_decode",
        description="Decode hexadecimal text back to plain text",
        family=SkillFamily.OPERATIONAL, handler_key="hex_decode",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["decoding", "hex", "utility"],
    ),
    Skill(
        action="html_encode", name="html_encode",
        description="HTML-encode text (escape special characters)",
        family=SkillFamily.OPERATIONAL, handler_key="html_encode",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["encoding", "html", "utility"],
    ),
    Skill(
        action="html_decode", name="html_decode",
        description="Decode HTML-encoded text",
        family=SkillFamily.OPERATIONAL, handler_key="html_decode",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["decoding", "html", "utility"],
    ),
    Skill(
        action="md5", name="md5",
        description="Compute MD5 hash of text",
        family=SkillFamily.OPERATIONAL, handler_key="md5",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["hashing", "md5", "utility"],
    ),
    Skill(
        action="sha1", name="sha1",
        description="Compute SHA-1 hash of text",
        family=SkillFamily.OPERATIONAL, handler_key="sha1",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["hashing", "sha1", "utility"],
    ),
    Skill(
        action="sha256", name="sha256",
        description="Compute SHA-256 hash of text",
        family=SkillFamily.OPERATIONAL, handler_key="sha256",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["hashing", "sha256", "utility"],
    ),
    Skill(
        action="sha512", name="sha512",
        description="Compute SHA-512 hash of text",
        family=SkillFamily.OPERATIONAL, handler_key="sha512",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["hashing", "sha512", "utility"],
    ),
    Skill(
        action="json_prettify", name="json_prettify",
        description="Pretty-print JSON with indentation",
        family=SkillFamily.OPERATIONAL, handler_key="json_prettify",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["json", "format", "utility"],
    ),
    Skill(
        action="json_minify", name="json_minify",
        description="Minify JSON by removing whitespace",
        family=SkillFamily.OPERATIONAL, handler_key="json_minify",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["json", "format", "utility"],
    ),
    Skill(
        action="csv_to_json", name="csv_to_json",
        description="Convert CSV data to JSON format",
        family=SkillFamily.OPERATIONAL, handler_key="csv_to_json",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["csv", "json", "conversion", "utility"],
    ),
    Skill(
        action="json_to_csv", name="json_to_csv",
        description="Convert JSON array to CSV format",
        family=SkillFamily.OPERATIONAL, handler_key="json_to_csv",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["json", "csv", "conversion", "utility"],
    ),
    Skill(
        action="kv_parse", name="kv_parse",
        description="Parse key=value pairs from text",
        family=SkillFamily.OPERATIONAL, handler_key="kv_parse",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["kv", "parsing", "utility"],
    ),
    Skill(
        action="xml_to_json", name="xml_to_json",
        description="Convert XML data to JSON format",
        family=SkillFamily.OPERATIONAL, handler_key="xml_to_json",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["xml", "json", "conversion", "utility"],
    ),
    Skill(
        action="json_parse", name="json_parse",
        description="Parse and validate JSON, returning structured data",
        family=SkillFamily.OPERATIONAL, handler_key="json_parse",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["json", "parsing", "utility"],
    ),
    Skill(
        action="csv_parse", name="csv_parse",
        description="Parse CSV data and return structured rows",
        family=SkillFamily.OPERATIONAL, handler_key="csv_parse",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["csv", "parsing", "utility"],
    ),
    Skill(
        action="text_upper", name="text_upper",
        description="Convert text to uppercase",
        family=SkillFamily.OPERATIONAL, handler_key="text_upper",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["text", "case", "utility"],
    ),
    Skill(
        action="text_lower", name="text_lower",
        description="Convert text to lowercase",
        family=SkillFamily.OPERATIONAL, handler_key="text_lower",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["text", "case", "utility"],
    ),
    Skill(
        action="text_reverse", name="text_reverse",
        description="Reverse the text string",
        family=SkillFamily.OPERATIONAL, handler_key="text_reverse",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["text", "reverse", "utility"],
    ),
    Skill(
        action="text_trim", name="text_trim",
        description="Trim leading and trailing whitespace from text",
        family=SkillFamily.OPERATIONAL, handler_key="text_trim",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["text", "trim", "utility"],
    ),
    Skill(
        action="line_sort", name="line_sort",
        description="Sort lines alphabetically",
        family=SkillFamily.OPERATIONAL, handler_key="line_sort",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["text", "sort", "utility"],
    ),
    Skill(
        action="unique_lines", name="unique_lines",
        description="Remove duplicate lines from text",
        family=SkillFamily.OPERATIONAL, handler_key="unique_lines",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["text", "dedup", "utility"],
    ),
    Skill(
        action="remove_empty_lines", name="remove_empty_lines",
        description="Remove empty and whitespace-only lines from text",
        family=SkillFamily.OPERATIONAL, handler_key="remove_empty_lines",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["text", "clean", "utility"],
    ),
    Skill(
        action="spl_escape", name="spl_escape",
        description="Escape special characters for use in SPL queries",
        family=SkillFamily.OPERATIONAL, handler_key="spl_escape",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["spl", "escape", "utility"],
    ),
    Skill(
        action="quote_values", name="quote_values",
        description="Quote values for safe inclusion in SPL or config files",
        family=SkillFamily.OPERATIONAL, handler_key="quote_values",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["spl", "quoting", "utility"],
    ),
    Skill(
        action="rex_extract", name="rex_extract",
        description="Extract fields using regex (rex-style extraction)",
        family=SkillFamily.OPERATIONAL, handler_key="rex_extract",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["regex", "extraction", "utility"],
    ),
    Skill(
        action="timestamp_convert", name="timestamp_convert",
        description="Convert between epoch timestamps and human-readable date formats",
        family=SkillFamily.OPERATIONAL, handler_key="timestamp_convert",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["timestamp", "epoch", "conversion", "utility"],
    ),
    Skill(
        action="uuid_generate", name="uuid_generate",
        description="Generate a random UUID (v4)",
        family=SkillFamily.OPERATIONAL, handler_key="uuid_generate",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["uuid", "generation", "utility"],
    ),
    Skill(
        action="regex_test", name="regex_test",
        description="Test a regex pattern against input text and show matches",
        family=SkillFamily.OPERATIONAL, handler_key="regex_test",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["regex", "testing", "utility"],
    ),
    Skill(
        action="conf_validate", name="conf_validate",
        description="Validate Splunk .conf file syntax and stanza structure",
        family=SkillFamily.OPERATIONAL, handler_key="conf_validate",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["conf", "validation", "splunk", "utility"],
    ),
    Skill(
        action="cim_validate", name="cim_validate",
        description="Validate CIM compliance of field names and data models",
        family=SkillFamily.OPERATIONAL, handler_key="cim_validate",
        approval=ApprovalGate.AUTO, intents=["data_transform"],
        min_role="VIEWER", tags=["cim", "validation", "splunk", "utility"],
    ),

    # =====================================================================
    # MIGRATION SKILLS — Splunk to Cribl migration tooling
    # =====================================================================
    Skill(
        action="analyze_splunk_confs", name="analyze_splunk_confs",
        description="Analyze Splunk configuration files (props.conf, transforms.conf) for index-time settings critical for Cribl migration",
        family=SkillFamily.OPERATIONAL, handler_key="analyze_splunk_confs",
        approval=ApprovalGate.AUTO,
        intents=["config_lookup", "cribl_config"],
        tags=["splunk", "cribl", "migration", "props", "transforms", "index-time"],
    ),
    Skill(
        action="compare_splunk_cribl", name="compare_splunk_cribl",
        description="Compare Splunk index-time configuration with Cribl pipeline and identify gaps",
        family=SkillFamily.OPERATIONAL, handler_key="compare_splunk_cribl",
        approval=ApprovalGate.AUTO,
        intents=["cribl_config", "cribl_pipeline"],
        tags=["splunk", "cribl", "migration", "comparison"],
    ),
    Skill(
        action="generate_cribl_pipeline", name="generate_cribl_pipeline",
        description="Generate Cribl pipeline configuration from Splunk props.conf and transforms.conf settings",
        family=SkillFamily.OPERATIONAL, handler_key="generate_cribl_pipeline",
        approval=ApprovalGate.CONFIRM,
        intents=["cribl_pipeline", "cribl_config"],
        tags=["cribl", "pipeline", "generation", "migration"],
    ),
]
